---
- name: demo
  hosts: demo
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo

  vars:
    netstat: True

  pre_tasks:
    - name: Load variables
      include_vars: vars/main.yml

  roles:
    - {role: checkdir}
    - {role: addconf}

  tasks:
    - block:
        - include_tasks: tasks/netstat.yaml
      when:  netstat

