---
cluster_cidr: "{{ [ansible_facts[cluster_interface].ipv4.network, ansible_facts[cluster_interface].ipv4.netmask] | join('/') | ipaddr('net') }}"

k8s_master_ports:
  - 2376/tcp
  - 6443/tcp
  - 8472/udp
  - 9099/tcp
  - 10250/tcp
  - 10254/tcp
  - 30000-32767/tcp
  - 30000-32767/udp

k8s_etcd_ports:
  - 2376/tcp
  - 2379-2380/tcp
  - 8472/udp
  - 9099/tcp
  - 10250/tcp

k8s_worker_ports:
  - 80/tcp
  - 443/tcp
  - 2376/tcp
  - 8472/udp
  - 9099/tcp
  - 10250/tcp
  - 10254/tcp
  - 30000-32767/tcp
  - 30000-32767/udp
